# Generated by Django 4.1 on 2023-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerinfo",
            name="created_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="investment",
            name="created_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateField(),
        ),
    ]
