# Generated by Django 4.1.3 on 2023-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_alter_customerinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='deleted_at',
            field=models.DateField(null=True),
        ),
    ]
