# Generated by Django 4.1 on 2023-03-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0002_alter_customerinfo_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="driver_fees",
            field=models.TextField(blank=True),
        ),
    ]
