# Generated by Django 4.1 on 2023-03-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0003_alter_investment_driver_fees"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customerinfo",
            name="deleted_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="investment",
            name="deleted_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="deleted_at",
            field=models.DateField(),
        ),
    ]
