# Generated by Django 4.1.3 on 2023-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_alter_customerinfo_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
