# Generated by Django 4.1.3 on 2023-03-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_alter_customerinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='created_at',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
