# Generated by Django 4.1 on 2023-03-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0004_order_payment_alter_customerinfo_deleted_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment",
            new_name="debt",
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
