# Generated by Django 4.1 on 2023-03-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0005_rename_payment_order_debt_order_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deleted_at",
            field=models.DateField(null=True),
        ),
    ]
