# Generated by Django 4.1.3 on 2023-03-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_alter_customerinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
