# Generated by Django 4.1 on 2023-03-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0007_alter_customerinfo_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="id",
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
    ]
