# Generated by Django 4.1 on 2023-03-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0008_remove_order_id_order_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
        migrations.AddField(
            model_name="order",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="investment",
            name="deleted_at",
            field=models.DateField(null=True),
        ),
    ]
