# Generated by Django 4.1 on 2023-03-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0009_remove_order_order_id_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
